const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { createHash } = require("node:crypto");
const root = path.resolve(__dirname, "..");
const checkout = path.join(root, "online-site");
const dist = path.join(checkout, "dist");
const pages = ["home.html", "index.html", "conversations.html", "vocab.html", "grammar.html", "grammar-quiz.html", "mistakes.html", "shadow-words.html", "tag.html", "textbook.html", "login.html"];
const assets = ["app.js", "app.css", "data.js", "vocab.js", "dialogues.js", "traps.js", "mic-worklet.js", "sandy-green-eyes.png", "sandy-meow-1.wav", "sandy-purr-1.wav"].map(file => `assets/${file}`);
const expected = [...pages, ...assets].sort();
const actual = fs.readdirSync(dist).flatMap(file => file === "assets" ? fs.readdirSync(path.join(dist, file)).map(asset => `assets/${asset}`) : file).sort();
assert.deepEqual(actual, expected, "Only the explicitly approved website files are uploaded.");
const digest = file => createHash("sha256").update(fs.readFileSync(file)).digest("hex");
for (const file of expected) assert.equal(digest(path.join(dist, file)), digest(path.join(root, file)), `${file}: deployment must match the latest website source`);
const manifest = JSON.parse(fs.readFileSync(path.join(checkout, ".openai/hosting.json")));
assert.ok(manifest.project_id && typeof manifest.project_id === "string");
assert.equal(manifest.static.directory, "dist");
assert.equal(fs.existsSync(path.join(checkout, ".local-speech")), false);
assert.ok(fs.readFileSync(path.join(root, ".gitignore"), "utf8").includes("online-site/"), "Keep the separate Sites checkout out of the GitHub source tree.");
console.log("PASS: private hosting package contains only 11 pages and 10 matching assets; no private runtime or learning files.");
